---
title: "draft code"
author: "John Nobles, Adam Gullion, Jonathan Aguilar"
date: "`r Sys.Date()`"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

# Variables of interest (hitting):

-   launch angle (`launch_angle_avg`)
-   exit velocity (`exit_velocity_avg`)
-   hard-hit rate (`hard_hit_percent`)
-   barrel batted rate (`barrel_batted_rate`)
-   strikeout percentage (`k_percent`)

```{r}
hitting <- read.csv('Qualified Hitting 2015-2024stats.csv')

#glimpse(hitting)

#hitting %>% select(launch_angle_avg)
```

# a

```{r}
hitting %>% 
  group_by(year) %>% 
  summarize(avg_launch_angle=mean(launch_angle_avg)) %>% 
  ggplot(aes(year, avg_launch_angle)) +
  geom_point() +
  theme_minimal() +
  geom_smooth()
```

# b

``` {r}
hitting %>% 
  ggplot(aes(as.factor(year), launch_angle_avg)) +
  geom_boxplot(outlier.color='red') +
  theme_bw()
```

# c

```{r}
hitting %>% 
  ggplot(aes(barrel_batted_rate, exit_velocity_avg)) +
  geom_point() +
  geom_smooth()
```

# d

```{r}
hitting %>% 
  ggplot(aes(as.factor(year), barrel_batted_rate)) +
  geom_boxplot(outlier.color='red') +
  theme_bw()
  
hitting %>% 
  group_by(year) %>% 
  summarize(avg_bbr=mean(barrel_batted_rate)) %>% 
  ggplot(aes(year, avg_bbr)) +
  geom_point() +
  theme_minimal() +
  geom_smooth()
```

# e

```{r}
hitting %>% 
  ggplot(aes(as.factor(year), exit_velocity_avg)) +
  geom_boxplot(outlier.color='red') +
  theme_bw()

hitting %>% 
  group_by(year) %>% 
  summarize(avg_exitv=mean(exit_velocity_avg)) %>% 
  ggplot(aes(year, avg_exitv)) +
  geom_point() +
  theme_minimal() +
  geom_smooth()
```

# f

```{r}
hitting %>% 
  ggplot(aes(as.factor(year), hard_hit_percent)) +
  geom_boxplot(outlier.color='red') +
  theme_bw()

hitting %>% 
  group_by(year) %>% 
  summarize(avg_hhp=mean(hard_hit_percent)) %>% 
  ggplot(aes(year, avg_hhp)) +
  geom_point() +
  theme_minimal() +
  geom_smooth()
```

# g

```{r}
hitting %>% 
  ggplot(aes(as.factor(year), k_percent)) +
  geom_boxplot(outlier.color='red') +
  theme_bw()

hitting %>% 
  group_by(year) %>% 
  summarize(avg_kp=mean(k_percent)) %>% 
  ggplot(aes(year, avg_kp)) +
  geom_point() +
  theme_minimal() +
  geom_smooth()
```

# Variables of interest (pitching)

- fast ball average velocity (`ff_avg_speed`)
- fast ball spin (`ff_avg_spin`)
- fast ball induced vertical break (`ff_avg_break_z_induced `)
- 

```{r}
pitching <- read.csv('QPitchingstats.csv')

glimpse(pitching)        
```




```{r}
pitching %>% select(-last_name..first_name, -player_id) %>% select(year, ff_avg_spin, ff_avg_speed, exit_velocity_avg, whiff_percent, hard_hit_percent, barrel_batted_rate, sweet_spot_percent, launch_angle_avg) %>% pairs()
```
# z

```{r}
# creates new column in pitching which contains the average hard hit percentage for each year
pitching %>% group_by(year) %>% mutate(avg_hhp_by_year=mean(hard_hit_percent)) %>% 
  ggplot(aes(as.factor(year), hard_hit_percent)) + 
  geom_boxplot() + 
  geom_point(aes(as.factor(year), avg_hhp_by_year), color='red', show.legend=TRUE) +
  theme_test() +
  labs(title='Hard hitting percentage by year',
       x='Year',
       y='Hard Hit %',
       color='Average HH% per year',
       legend='a')
  

```


