---
title: "Jonathans Section"
author: "Jonathan"
date: "2025-04-15"
output: slidy_presentation
---

#```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
#```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```


```{r}
hitting <- read.csv('Qualified Hitting 2015-2024stats.csv')

#glimpse(hitting)

#hitting %>% select(launch_angle_avg)

hitting
```

#

```{r}
hits_2015 = hitting %>% 
  filter(year == 2015) %>% select(hit) %>% unlist() %>% mean()



hits_2016 = hitting %>% 
  filter(year == 2016) %>% select(hit) %>% unlist() %>% mean()

hits_2017 = hitting %>% 
  filter(year == 2017) %>% select(hit) %>% unlist() %>% mean()

hits_2018 = hitting %>% 
  filter(year == 2018) %>% select(hit) %>% unlist() %>% mean()

hits_2019 = hitting %>% 
  filter(year == 2019) %>% select(hit) %>% unlist() %>% mean()

hits_2020 = hitting %>% 
  filter(year == 2020) %>% select(hit) %>% unlist() %>% mean()

hits_2021 = hitting %>% 
  filter(year == 2021) %>% select(hit) %>% unlist() %>% mean()

hits_2022 = hitting %>% 
  filter(year == 2022) %>% select(hit) %>% unlist() %>% mean()

hits_2023 = hitting %>% 
  filter(year == 2023) %>% select(hit) %>% unlist() %>% mean()

hits_2024 = hitting %>% 
  filter(year == 2024) %>% select(hit) %>% unlist() %>% mean()

hits = c(hits_2015,hits_2016,hits_2017,hits_2018,hits_2019,hits_2020,hits_2021,hits_2022,hits_2023,hits_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)

data <- data.frame(years,hits)

# Plot
ggplot(data,aes(x=years, y=hits)) + scale_x_discrete(limits = years) + ylim(0,200) + geom_line()
```

#

```{r}
hitting %>% ggplot(aes(x = as.factor(year),y = hit)) + geom_point() 

```


```{r}
pitching <- read.csv('QPitchingstats.csv')

pitching
```

```{r}
pitching %>% ggplot(aes(x = as.factor(year),y = p_game)) + geom_point() 
```

```{r}
abs_2015 = pitching %>% 
  filter(year == 2015) %>% select(p_game) %>% unlist() %>% mean()

abs_2016 = pitching %>% 
  filter(year == 2016) %>% select(p_game) %>% unlist() %>% mean()

abs_2017 = pitching %>% 
  filter(year == 2017) %>% select(p_game) %>% unlist() %>% mean()

abs_2018 = pitching %>% 
  filter(year == 2018) %>% select(p_game) %>% unlist() %>% mean()

abs_2019 = pitching %>% 
  filter(year == 2019) %>% select(p_game) %>% unlist() %>% mean()

abs_2020 = pitching %>% 
  filter(year == 2020) %>% select(p_game) %>% unlist() %>% mean()

abs_2021 = pitching %>% 
  filter(year == 2021) %>% select(p_game) %>% unlist() %>% mean()

abs_2022 = pitching %>% 
  filter(year == 2022) %>% select(p_game) %>% unlist() %>% mean()

abs_2023 = pitching %>% 
  filter(year == 2023) %>% select(p_game) %>% unlist() %>% mean()

abs_2024 = pitching %>% 
  filter(year == 2024) %>% select(p_game) %>% unlist() %>% mean()

p_game = c(abs_2015,abs_2016,abs_2017,abs_2018,abs_2019,abs_2020,abs_2021,abs_2022,abs_2023,abs_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)
```



```{r}
data <- data.frame(years,p_game)

# Plot
```


```{r}
ggplot(data,aes(x=years, y=p_game)) + scale_x_discrete(limits = years) + ylim(0,35) + geom_line()
```

#

```{r}
abs_2015 = pitching %>% 
  filter(year == 2015) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2016 = pitching %>% 
  filter(year == 2016) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2017 = pitching %>% 
  filter(year == 2017) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2018 = pitching %>% 
  filter(year == 2018) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2019 = pitching %>% 
  filter(year == 2019) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2020 = pitching %>% 
  filter(year == 2020) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2021 = pitching %>% 
  filter(year == 2021) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2022 = pitching %>% 
  filter(year == 2022) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2023 = pitching %>% 
  filter(year == 2023) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2024 = pitching %>% 
  filter(year == 2024) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

ffavgspin = c(abs_2015,abs_2016,abs_2017,abs_2018,abs_2019,abs_2020,abs_2021,abs_2022,abs_2023,abs_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)


data <- data.frame(years,ffavgspin)

# Plot
ggplot(data,aes(x=years, y=ffavgspin)) + scale_x_discrete(limits = years) + ylim(0,3000) + geom_line()

```

#

```{r}
abs_2015 = hitting %>% 
  filter(year == 2015) %>% select(launch_angle_avg) %>% unlist() %>% mean()

abs_2016 = hitting %>% 
  filter(year == 2016) %>% select(launch_angle_avg) %>% unlist() %>% mean()

abs_2017 = hitting %>% 
  filter(year == 2017) %>% select(launch_angle_avg) %>% unlist() %>% mean()

abs_2018 = hitting %>% 
  filter(year == 2018) %>% select(launch_angle_avg) %>%  unlist() %>% mean()

abs_2019 = hitting %>% 
  filter(year == 2019) %>% select(launch_angle_avg) %>% unlist() %>% mean()

abs_2020 = hitting %>% 
  filter(year == 2020) %>% select(launch_angle_avg) %>% unlist() %>% mean()

abs_2021 = hitting %>% 
  filter(year == 2021) %>% select(launch_angle_avg) %>% unlist() %>% mean()

abs_2022 = hitting %>% 
  filter(year == 2022) %>% select(launch_angle_avg) %>% unlist() %>% mean()

abs_2023 = hitting %>% 
  filter(year == 2023) %>% select(launch_angle_avg) %>% unlist() %>% mean()

abs_2024 = hitting %>% 
  filter(year == 2024) %>% select(launch_angle_avg) %>% unlist() %>% mean()


launch_angle_avg = c(abs_2015,abs_2016,abs_2017,abs_2018,abs_2019,abs_2020,abs_2021,abs_2022,abs_2023,abs_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)


data <- data.frame(years,launch_angle_avg)

# Plot
ggplot(data,aes(x=years, y=launch_angle_avg))+ scale_x_discrete(limits = years) + ylim(10,14) + geom_line()
```

#

```{r}
abs_2015 = hitting %>% 
  filter(year == 2015) %>% select(flyballs_percent) %>% unlist() %>% mean()

abs_2016 = hitting %>% 
  filter(year == 2016) %>% select(flyballs_percent) %>% unlist() %>% mean()

abs_2017 = hitting %>% 
  filter(year == 2017) %>% select(flyballs_percent) %>% unlist() %>% mean()

abs_2018 = hitting %>% 
  filter(year == 2018) %>% select(flyballs_percent) %>%  unlist() %>% mean()

abs_2019 = hitting %>% 
  filter(year == 2019) %>% select(flyballs_percent) %>% unlist() %>% mean()

abs_2020 = hitting %>% 
  filter(year == 2020) %>% select(flyballs_percent) %>% unlist() %>% mean()

abs_2021 = hitting %>% 
  filter(year == 2021) %>% select(flyballs_percent) %>% unlist() %>% mean()

abs_2022 = hitting %>% 
  filter(year == 2022) %>% select(flyballs_percent) %>% unlist() %>% mean()

abs_2023 = hitting %>% 
  filter(year == 2023) %>% select(flyballs_percent) %>% unlist() %>% mean()

abs_2024 = hitting %>% 
  filter(year == 2024) %>% select(flyballs_percent) %>% unlist() %>% mean()


flyballs_percent = c(abs_2015,abs_2016,abs_2017,abs_2018,abs_2019,abs_2020,abs_2021,abs_2022,abs_2023,abs_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)


data <- data.frame(years,flyballs_percent)

# Plot
ggplot(data,aes(x=years, y=flyballs_percent)) + ylab("Flyball percentage ") + scale_x_discrete(limits = years) + geom_line()

```

#

```{r}
abs_2015 = hitting %>% 
  filter(year == 2015) %>% select(flyballs) %>% unlist() %>% mean()

abs_2016 = hitting %>% 
  filter(year == 2016) %>% select(flyballs) %>% unlist() %>% mean()

abs_2017 = hitting %>% 
  filter(year == 2017) %>% select(flyballs) %>% unlist() %>% mean()

abs_2018 = hitting %>% 
  filter(year == 2018) %>% select(flyballs) %>%  unlist() %>% mean()

abs_2019 = hitting %>% 
  filter(year == 2019) %>% select(flyballs) %>% unlist() %>% mean()

abs_2020 = hitting %>% 
  filter(year == 2020) %>% select(flyballs) %>% unlist() %>% mean()

abs_2021 = hitting %>% 
  filter(year == 2021) %>% select(flyballs) %>% unlist() %>% mean()

abs_2022 = hitting %>% 
  filter(year == 2022) %>% select(flyballs) %>% unlist() %>% mean()

abs_2023 = hitting %>% 
  filter(year == 2023) %>% select(flyballs) %>% unlist() %>% mean()

abs_2024 = hitting %>% 
  filter(year == 2024) %>% select(flyballs) %>% unlist() %>% mean()


flyballs = c(abs_2015,abs_2016,abs_2017,abs_2018,abs_2019,abs_2020,abs_2021,abs_2022,abs_2023,abs_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)


data <- data.frame(years,flyballs)

# Plot
ggplot(data,aes(x=years, y=flyballs))+ scale_x_discrete(limits = years) + ylim(0,120) + geom_line()
```

#

```{r}
abs_2015 = pitching %>% 
  filter(year == 2015) %>% select(ff_avg_spin) %>% filter(!is.na(ff_avg_spin)) %>% unlist() %>% mean()

abs_2016 = pitching %>% 
  filter(year == 2016) %>% select(ch_avg_spin) %>% filter(!is.na(ch_avg_spin)) %>% unlist() %>% mean()

abs_2017 = pitching %>% 
  filter(year == 2017) %>% select(ch_avg_spin) %>% filter(!is.na(ch_avg_spin)) %>% unlist() %>% mean()

abs_2018 = pitching %>% 
  filter(year == 2018) %>% select(ch_avg_spin) %>% filter(!is.na(ch_avg_spin)) %>% unlist() %>% mean()

abs_2019 = pitching %>% 
  filter(year == 2019) %>% select(ch_avg_spin) %>% filter(!is.na(ch_avg_spin)) %>% unlist() %>% mean()

abs_2020 = pitching %>% 
  filter(year == 2020) %>% select(ch_avg_spin) %>% filter(!is.na(ch_avg_spin)) %>% unlist() %>% mean()

abs_2021 = pitching %>% 
  filter(year == 2021) %>% select(ch_avg_spin) %>% filter(!is.na(ch_avg_spin)) %>% unlist() %>% mean()

abs_2022 = pitching %>% 
  filter(year == 2022) %>% select(ch_avg_spin) %>% filter(!is.na(ch_avg_spin)) %>% unlist() %>% mean()

abs_2023 = pitching %>% 
  filter(year == 2023) %>% select(ch_avg_spin) %>% filter(!is.na(ch_avg_spin)) %>% unlist() %>% mean()

abs_2024 = pitching %>% 
  filter(year == 2024) %>% select(ch_avg_spin) %>% filter(!is.na(ch_avg_spin)) %>% unlist() %>% mean()

ch_avg_spin = c(abs_2015,abs_2016,abs_2017,abs_2018,abs_2019,abs_2020,abs_2021,abs_2022,abs_2023,abs_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)


data <- data.frame(years,ch_avg_spin)

# Plot
ggplot(data,aes(x=years, y=ch_avg_spin)) + scale_x_discrete(limits = years) + ylim(0,3000) + geom_line()

```

#

```{r}
hits_2015 = hitting %>% 
  filter(year == 2015) %>% select(linedrives_percent) %>% unlist() %>% mean()

hits_2016 = hitting %>% 
  filter(year == 2016) %>% select(linedrives_percent) %>% unlist() %>% mean()

hits_2017 = hitting %>% 
  filter(year == 2017) %>% select(linedrives_percent) %>% unlist() %>% mean()

hits_2018 = hitting %>% 
  filter(year == 2018) %>% select(linedrives_percent) %>% unlist() %>% mean()

hits_2019 = hitting %>% 
  filter(year == 2019) %>% select(linedrives_percent) %>% unlist() %>% mean()

hits_2020 = hitting %>% 
  filter(year == 2020) %>% select(linedrives_percent) %>% unlist() %>% mean()

hits_2021 = hitting %>% 
  filter(year == 2021) %>% select(linedrives_percent) %>% unlist() %>% mean()

hits_2022 = hitting %>% 
  filter(year == 2022) %>% select(linedrives_percent) %>% unlist() %>% mean()

hits_2023 = hitting %>% 
  filter(year == 2023) %>% select(linedrives_percent) %>% unlist() %>% mean()

hits_2024 = hitting %>% 
  filter(year == 2024) %>% select(linedrives_percent) %>% unlist() %>% mean()

linedrives_percent = c(hits_2015,hits_2016,hits_2017,hits_2018,hits_2019,hits_2020,hits_2021,hits_2022,hits_2023,hits_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)

data <- data.frame(years,linedrives_percent)

# Plot
ggplot(data,aes(x=years, y=linedrives_percent)) + scale_x_discrete(limits = years) + ylim(0,50) + geom_line()

```

#

```{r}
hits_2015 = hitting %>% 
  filter(year == 2015) %>% select(swing_percent) %>% unlist() %>% mean()



hits_2016 = hitting %>% 
  filter(year == 2016) %>% select(swing_percent) %>% unlist() %>% mean()

hits_2017 = hitting %>% 
  filter(year == 2017) %>% select(swing_percent) %>% unlist() %>% mean()

hits_2018 = hitting %>% 
  filter(year == 2018) %>% select(swing_percent) %>% unlist() %>% mean()

hits_2019 = hitting %>% 
  filter(year == 2019) %>% select(swing_percent) %>% unlist() %>% mean()

hits_2020 = hitting %>% 
  filter(year == 2020) %>% select(swing_percent) %>% unlist() %>% mean()

hits_2021 = hitting %>% 
  filter(year == 2021) %>% select(swing_percent) %>% unlist() %>% mean()

hits_2022 = hitting %>% 
  filter(year == 2022) %>% select(swing_percent) %>% unlist() %>% mean()

hits_2023 = hitting %>% 
  filter(year == 2023) %>% select(swing_percent) %>% unlist() %>% mean()

hits_2024 = hitting %>% 
  filter(year == 2024) %>% select(swing_percent) %>% unlist() %>% mean()

swing_percent = c(hits_2015,hits_2016,hits_2017,hits_2018,hits_2019,hits_2020,hits_2021,hits_2022,hits_2023,hits_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)

data <- data.frame(years,swing_percent)

# Plot
ggplot(data,aes(x=years, y=swing_percent)) + scale_x_discrete(limits = years) + ylim(0,100) + geom_line()
```

#

```{r}
hits_2015 = hitting %>% 
  filter(year == 2015) %>% select(ab) %>% unlist() %>% mean()



hits_2016 = hitting %>% 
  filter(year == 2016) %>% select(ab) %>% unlist() %>% mean()

hits_2017 = hitting %>% 
  filter(year == 2017) %>% select(ab) %>% unlist() %>% mean()

hits_2018 = hitting %>% 
  filter(year == 2018) %>% select(ab) %>% unlist() %>% mean()

hits_2019 = hitting %>% 
  filter(year == 2019) %>% select(ab) %>% unlist() %>% mean()

hits_2020 = hitting %>% 
  filter(year == 2020) %>% select(ab) %>% unlist() %>% mean()

hits_2021 = hitting %>% 
  filter(year == 2021) %>% select(ab) %>% unlist() %>% mean()

hits_2022 = hitting %>% 
  filter(year == 2022) %>% select(ab) %>% unlist() %>% mean()

hits_2023 = hitting %>% 
  filter(year == 2023) %>% select(ab) %>% unlist() %>% mean()

hits_2024 = hitting %>% 
  filter(year == 2024) %>% select(ab) %>% unlist() %>% mean()

ab = c(hits_2015,hits_2016,hits_2017,hits_2018,hits_2019,hits_2020,hits_2021,hits_2022,hits_2023,hits_2024)
years = c(2015,2016,2017,2018,2019,2020,2021,2022,2023,2024)

data <- data.frame(years,ab)

# Plot
ggplot(data,aes(x=years, y=ab)) + scale_x_discrete(limits = years) + ylim(0,600) + geom_line()

```